baseurl = "/"
title = "Sugarblood"
copyright = "Copyright (c) 2025, all rights reserved."
canonifyurls = true
languageCode = "en-US"
pagination.pagerSize = 3
theme = "hugo-dusk"

googleAnalytics = "G-3HS071YZGC"
disqusShortname = ""

[params.author]
  name = "sugarblood"

SectionPagesMenu = "main"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech, hacking, cybersecurity, AI, ML, machine learning, personal"
  description = "A beginnning to a second brain possibly, or maybe just a dump site for tutorials for myself for later."
[params.meta.fediverse]
  creator = "@usename@mastodon.server" # https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/

[params]
  github = "Sugarbl00d"
  linkedin = "linkedin id"
  email = "jared@ltr.dev"
  theme_colors = "default-dark" # uses color css file under static/css/default-dark.css
  utterancesRepo="REPO_NAME" # Utterances is enabled when this param is set
  utterancesTheme="github-dark" # Default: github-dark
  utterancesIssueTerm="pathname" # Default: pathname
[params.mastodon] # https://joinmastodon.org/verification
  username = "username"
  server = "https://example.com"